Fix include path of msgpack-modelica.h
Header msgpack-modelica.h requires that "modelica://MessagePack/Resources/Include" is on the include path. This is not the case for generated C code from tools like SimulationX which take "modelica://MessagePack/Resources/C-Sources/msgpack-c/include" as set by the IncludeDirectory annotation as include path.

This fixes the include error
```
c:\Projekte\msgpack-modelica\MessagePack\Resources\C-Sources\msgpack-c\include\../../../Include/msgpack-modelica.h(50) : fatal error C1083: Cannot open include file: '../C-Sources/msgpack-c/include/msgpack.h': No such file or directory
```
of generated C code from Dymola or SimulationX. It is necessary to only have one include directory (which is "modelica://MessagePack/Resources/C-Sources/msgpack-c/include") for the VS2010 build project and the generated C code from the simulation tools.